### ISSUE TITLE
This is awesome! Add screenshot to README

### ISSUE THREAD

**Issue by siznax** [jxb345/78sidekick#10]
![Screen Shot 2019-09-06 at 2 34 24 PM](https://user-images.githubusercontent.com/44357/64461967-b374a400-d0b3-11e9-95ab-1bb4db712db7.png)

**Comment by jxb345** [comment]
A screenshot has been added to the README.md. Note: I took a different screenshot showing "John Lee Hooker" as the artist of the current song (as to hopefully pique interest in the app given he's such a famous musician).
