### ISSUE TITLE
npx needs to be added as a dependency

### ISSUE THREAD

**Issue by mekarpeles** [jxb345/78sidekick#8]

**Comment by siznax** [comment]
Also, `nodemon`:

```
$ npm run start

> 78-browser@1.0.0 start /Users/steve/Code/78sidekick
> nodemon ./server.js

sh: nodemon: command not found
```

**Comment by mekarpeles** [comment]
@siznax I hit this too! Great catch. Moving this to it's own issue if that's OK :)

**Comment by siznax** [comment]
Nice work!

**Comment by jxb345** [comment]
Upgraded npm (npm@5.2 includes npx) and installed the npx package individually (though this is redundant). Thanks for taking the time to report this issue!
